[package]
name = "direct"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
puppy-core = { path = "../puppy-core" }
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
