[package]
name = "tun"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
puppy-core = { path = "../puppy-core" }
config = { path = "../config" }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
smoltcp = { workspace = true, features = ["proto-ipv4", "proto-ipv6", "socket-tcp", "socket-udp", "socket-dns", "alloc", "medium-ip"] }
nix = { workspace = true }
libc = { workspace = true }
socket2 = { workspace = true, features = ["all"] }
parking_lot = { workspace = true }
bytes = { workspace = true }
tokio-util = { version = "0.7", features = ["rt"] }

[dev-dependencies]
tokio-test = { workspace = true }
