[package]
name = "socksproxy-fe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
puppy-core = { path = "../puppy-core" }
config = { path = "../config" }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
rcgen = "0.13"
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
tokio-rustls = { workspace = true }
async-trait = { workspace = true }
puppy-core = { path = "../puppy-core" }
direct = { path = "../direct" }
